# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# To install the pre-commit hook: pre-commit install
# To run the command: pre-commit run --all-files

fail_fast: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: mixed-line-ending
            args: ['--fix=lf']
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: detect-private-key
          - id: detect-aws-credentials
            args: ['--allow-missing-credentials']

    - repo: https://github.com/sirosen/texthooks
      rev: 0.7.1
      hooks:
          - id: fix-smartquotes

    - repo: https://github.com/MaratFM/pre-commit-remark
      rev: 1.0.0
      hooks:
          - id: remark
            args: ['--output', '--frail']
            files: "\\.md$"
            exclude: .vscode|assets/models|sponge/deps
